name: CICD
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Generate Deployment Package
        run: zip -r Forums-Reviews-Backend-build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'ForumNReview-kavya-backend'
          environment_name: 'ForumNReview-kavya-backend-env'
          version_label: ${{ github.sha }}
          region: eu-west-1
          deployment_package: Forums-Reviews-Backend-build.zip
          use_existing_version_if_available: true
      - name: Cleanup
        run: rm Forums-Reviews-Backend-build.zip
